### Neural Network Basics

In [1]:
# imports
import numpy as np

### Perceptron
Consider we have 2 inputs (x1 and x2) and 3 fully connected neurons (1, 2 and 3).

X : Input matrix, each row is one example and each column is one feature

In [3]:
# Input features

X = np.array([[2, 4], [5, 8], [9, 12]])
X

array([[ 2,  4],
       [ 5,  8],
       [ 9, 12]])

W : Weight matrix, each row contains weights corresponding to one feature (check column in X) e.g. w1 for x1, but each column contain weights for each neuron. As many neurons, as many weight columns

In [12]:
W = np.array([[1.5, 2.5, 1.2], [0.5, 0.8, 0.3]])
W

array([[1.5, 2.5, 1.2],
       [0.5, 0.8, 0.3]])

In [13]:
# bias term
b = np.array([2, 4, 6])
b

array([2, 4, 6])

So 1.5 -> 2 and 0.5 -> 4 for neuron 1.

The final output is given as h = activation_function(z)

z = XW + b

In [14]:
z = np.matmul(X, W) + b
z

array([[ 7. , 12.2,  9.6],
       [13.5, 22.9, 14.4],
       [21.5, 36.1, 20.4]])